<div class="row">
    <div class="col-md-9">
        <br /><br />
        <section>
            <div class="formulario">
                <h6>Cadastrar</h6>
                <form action="/create" method="post" id="validate">

                    <label>* Nome</label>
                    <input name="name" type="text" class="g">

                    <label>* E-mail</label>
                    <input name="mail" type="text" class="g">

                    <label>Senha</label>
                    <input name="password" type="password" class="p" id="telefone">


                    <input type="submit" value="Enviar">

                </form>
            </div><!--/formulario-->

        </section>
    </div>
</div>

