<div class="row">




    <div class="col-md-9">

        <section>
            <div class="formulario">
                <h6>Editar</h6>
                <form action="" method="post" id="validate">

                    <label>* Nome</label>
                    <input name="name" type="text" value="<?php echo $data->name; ?>" class="g">

                    <label>* E-mail</label>
                    <input name="mail" type="text" value="<?php echo $data->mail; ?>" class="g">

                    <label>Senha</label>
                    <input name="password" type="password" class="p">


                    <input type="submit" value="Enviar">

                </form>
            </div><!--/formulario-->


        </section>
    </div>

</div>

